### ISSUE TITLE
redis集群最后一步删除临时主节点

### ISSUE THREAD

**Issue by flyfish0087** [zhuchuangang/k8s-install-scripts#17]
通过您的yaml创建的redis集群执行到最后一步，删除了临时主机点，但是不会产生新的主节点，请问这是怎么回事？

**Comment by zhuchuangang** [comment]
仲裁节点需要等待一段时间会从salve节点中会选举出主节点

**Comment by flyfish0087** [comment]
但是很长时间没选举成主节点，这个怎么分析问题？
而且sentienl的日志都是这样：
Could not connect to Redis at -p:6379: Name or service not known
Could not connect to Redis at 10.2.84.117:6379: Connection refused
Connecting to master failed.  Waiting..

**Comment by zhuchuangang** [comment]
可以看一下是不是kubernetes集群的网络有问题，主机之间的pod ip或cluster ip不通，所有控制器做了非亲和调度，pod会分布在不同的主机上，如果pod ip或cluster ip不通，redis集群自然起不来。

**Comment by flyfish0087** [comment]
后面确实可以了，谢谢博主，你的项目棒棒的^_^
