### ISSUE TITLE
kubectl create -f kubedns-controller.yaml报错请教

### ISSUE THREAD

**Issue by shilei990** [zhuchuangang/k8s-install-scripts#18]
[root@k8s ~]# kubectl create -f kubedns-controller.yaml
error: error validating "kubedns-controller.yaml": error validating data: [found invalid field tolerations for v1.PodSpec, found invalid field optional for v1.ConfigMapVolumeSource]; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by zhuchuangang** [comment]
kubedns脚本较老apiVersion: extensions/v1beta1,你当前集群的api版本应该比较高有些字段应该已经调整，建议到kubernetes的github仓库获取最新的kubedns脚本，或者使用rke安装k8s环境，开箱即用，文档如下https://github.com/zhuchuangang/k8s-install-scripts/tree/master/rke
