### ISSUE TITLE
1.7.2版本脚本错误

### ISSUE THREAD

**Issue by sunsky-cn** [zhuchuangang/k8s-install-scripts#6]
kubeadm init --apiserver-advertise-address=${MASTER_ADDRESS} --kubernetes-version=v${KUBE_VERSION} --token=${KUBE_TOKEN} --pod-network-cidr=10.244.0.0/12
会导致容器无法不匹配iptables的策略，无法snat而无法访问外网

这里的网段掩码有误应该是 --pod-network-cidr=10.244.0.0/16

**Comment by zhuchuangang** [comment]
是的，和flannel脚本是不一致，已经做了修改

**Comment by sunsky-cn** [comment]
能给个联系方式吗？kubadm做自动pv，rbd方式卡主了。。。想请教下
